"""added personality traits to Cat Model

Revision ID: 1067da0f1691
Revises: 
Create Date: 2024-07-17 16:10:13.246064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1067da0f1691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_level', sa.Enum('LOW', 'MODERATE', 'HIGH', name='activitylevelenum'), nullable=True))
        batch_op.add_column(sa.Column('temperament', sa.Enum('CALM', 'FRIENDLY', 'PLAYFUL', name='temperamentenum'), nullable=True))
        batch_op.add_column(sa.Column('affection_level', sa.Enum('LOW', 'MODERATE', 'HIGH', name='affectionlevelenum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cats', schema=None) as batch_op:
        batch_op.drop_column('affection_level')
        batch_op.drop_column('temperament')
        batch_op.drop_column('activity_level')

    # ### end Alembic commands ###
