"""added even more traits to Cat Model

Revision ID: 38b40dd64a49
Revises: 1067da0f1691
Create Date: 2024-07-17 16:39:49.345822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b40dd64a49'
down_revision = '1067da0f1691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energy_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='energylevelenum'), nullable=True))
        batch_op.add_column(sa.Column('socialization', sa.Enum('FRIENDLY_WITH_CATS', 'FRIENDLY_WITH_DOGS', 'FRIENDLY_WITH_OTHER_ANIMALS', name='socializationenum'), nullable=True))
        batch_op.add_column(sa.Column('independence', sa.Enum('SOLO', 'COMPANY', name='independenceenum'), nullable=True))
        batch_op.add_column(sa.Column('curiosity', sa.Enum('INQUISITIVE', 'CAUTIOUS', name='curiosityenum'), nullable=True))
        batch_op.add_column(sa.Column('cuddliness', sa.Enum('LOVES_CUDDLING', 'PERSONAL_SPACE', name='cuddlinessenum'), nullable=True))
        batch_op.alter_column('temperament',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PLAYFUL', 'RELAXED', 'SHY', 'ADVENTUROUS', name='temperamentenum'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cats', schema=None) as batch_op:
        batch_op.alter_column('temperament',
               existing_type=sa.Enum('PLAYFUL', 'RELAXED', 'SHY', 'ADVENTUROUS', name='temperamentenum'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.drop_column('cuddliness')
        batch_op.drop_column('curiosity')
        batch_op.drop_column('independence')
        batch_op.drop_column('socialization')
        batch_op.drop_column('energy_level')

    # ### end Alembic commands ###
